apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal-backend
  namespace: job-portal
  labels:
    app: job-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-portal
  template:
    metadata:
      labels:
        app: job-portal
    spec:
      containers:
      - name: job-portal-backend
        image: stenny17/job-portal-backend:latest
        ports:
        - containerPort: 8000

