apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal-backend
  labels:
    app: job-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-portal
  template:
    metadata:
      labels:
        app: job-portal
    spec:
      containers:
        - name: job-portal-backend
          image: docker.io/stenny17/job-portal-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"

