apiVersion: v1
kind: Service
metadata:
  name: job-portal-backend-service
spec:
  type: LoadBalancer
  selector:
    app: job-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

