name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: stenny17/job-portal-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          cd backend
          pytest tests/

      - name: Run Static Code Analysis
        run: |
          cd backend
          pip install pylint
          pylint main.py || true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE ./backend

      - name: Push Docker Image to Docker Hub
        run: |
          docker push $DOCKER_IMAGE

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull $DOCKER_IMAGE
            docker stop job-portal || true
            docker rm job-portal || true
            docker run -d --name job-portal -p 80:80 $DOCKER_IMAGE

