name: CI/CD Pipeline with Argo CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: stenny1710/job-portal-backend
  TAG: ${{ github.sha }}
  CLUSTER_NAME: stenny-eks-cluster
  AWS_REGION: us-west-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Run Unit Tests
      run: |
        pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:$TAG ./backend
        docker push $IMAGE_NAME:$TAG

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update Argo CD App
      run: |
        kubectl apply -f manifests/deployment.yaml
        kubectl rollout restart deployment jobportal-deployment

