- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.10'

- name: Install Python dependencies
  run: |
    cd backend
    python -m pip install --upgrade pip
    pip install -r requirements.txt

